[package]
name = "vespetrel-imap"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "IMAP client with IDLE, CONDSTORE, QRESYNC, XOAUTH2"

[dependencies]
vespetrel-core = { path = "../vespetrel-core" }
tokio = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
imap-codec = { workspace = true }
imap-types = { workspace = true }
mail-parser = { workspace = true }
base64 = "0.22"
rustls = { workspace = true }
memchr = { workspace = true }
chrono = { workspace = true }

