[package]
name = "vespetrel-render"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
description = "HTML sanitization, tracker stripping, markdown render pipeline"

[dependencies]
tracing = { workspace = true }
ammonia = { workspace = true }
lol_html = { workspace = true }
mail-parser = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
simdutf8 = { workspace = true }
memchr = { workspace = true }
ahash = { workspace = true }
regex = { workspace = true }
url = { workspace = true }
urlencoding = { workspace = true }


